name: schoolspot
description: "A school finding application for students."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  file_picker: ^6.2.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.2
  charts_flutter: ^0.12.0
  url_launcher: ^6.0.10
  palette_generator: ^0.3.3+3
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/usls.png
    - assets/images/san-ag.png
    - assets/images/unor.jpeg
    - assets/images/rci.png
    - assets/images/logo.png
    - assets/images/cet.png
    - assets/images/cba.png
    - assets/images/con.png
    - assets/images/cod.png
    - assets/images/cas.png
    